FROM maven:3.9.6-eclipse-temurin-17 AS build
WORKDIR /app

COPY pom.xml .
COPY common ./common
COPY crawler-service ./crawler-service
COPY indexer-service ./indexer-service
COPY search-service ./search-service

RUN mvn -pl search-service -am clean package -DskipTests

FROM eclipse-temurin:17-jre
WORKDIR /app
COPY --from=build /app/search-service/target/*.jar app.jar
ENTRYPOINT ["java", "-jar", "app.jar"]
